### ISSUE TITLE
Bug: Can't use J-RTP commands in console.

### ISSUE THREAD

**Issue by lokka30** [donvi-bz/JakesRTP#3]
Running the `rtp` and `rtp-admin` commands in console don't do anything. No error messages, just silence.

**Comment by JakeTS** [comment]
The `rtp` command _only_ works on the player who ran it, for teleporting from console you need to use `forcertp`.

The `rtp-admin` command is like... 80% functional, so I'll leave this bug open for that reason.

**Comment by donvi-bz** [comment]
No longer relevant.
