### ISSUE TITLE
Broken discord invite link

### ISSUE THREAD

**Issue by WiIIiam278** [donvi-bz/JakesRTP#9]
Hi, sorry for filing an issue for something relatively trivial - though I wasn't sure of any other way of contacting you. Your discord link on the spigot resource thread is broken and I'm unable to join it. 
Please could you generate a new invite link, perhaps also add it to the body of the readme? Feel free to delete this issue at your discretion.
Many thanks!

**Comment by donvi-bz** [comment]
Thanks for catching that! It has been updated on the spigot page and I will add it here too.
